<a href="https://colab.research.google.com/github/ZungLV/AI/blob/main/Train_Face.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from os import listdir
from numpy import asarray, save
from keras.utils import load_img, img_to_array, to_categorical

folder = '/content/drive/MyDrive/Datasets AI/'
photos,labels = list(), list()

for file in listdir(data):
  output=0
  if file.startswith('Dung'):
    output = 1
  if file.startswith('Hanh'):
    output = 2
  if file.startswith('Truc'):
    output = 3
  if file.startswith('Phat'):
    output = 4
  if file.startswith('Phuc'):
    output = 5
  photo = load_img(folder + file,target_size=(192,257))
  photo = img_to_array(photo)
  photos.append(photo)
  labels.append(output)

photos = asarray(photos)
labels = asarray(labels)
labels = to_categorical(labels)

print(photos.shape,labels.shape)
print(photos)

save('/content/drive/MyDrive/Colab Notebooks/Test 1 AI/AIdata_photo.npy',photos)
save('/content/drive/MyDrive/Colab Notebooks/Test 1 AI/AIdata_label.npy',labels)


(577, 192, 257, 3) (577, 6)
[[[[153. 155. 154.]
   [155. 155. 155.]
   [154. 154. 154.]
   ...
   [ 50.  50.  52.]
   [ 54.  54.  54.]
   [ 54.  54.  52.]]

  [[154. 156. 155.]
   [155. 155. 155.]
   [154. 154. 154.]
   ...
   [ 38.  38.  38.]
   [ 50.  50.  50.]
   [ 57.  57.  55.]]

  [[156. 158. 157.]
   [154. 156. 155.]
   [153. 153. 153.]
   ...
   [ 30.  30.  30.]
   [ 48.  48.  48.]
   [ 49.  49.  49.]]

  ...

  [[166. 167. 172.]
   [168. 169. 174.]
   [164. 165. 169.]
   ...
   [ 61.  61.  61.]
   [ 58.  56.  57.]
   [ 58.  56.  57.]]

  [[168. 168. 176.]
   [167. 167. 175.]
   [165. 166. 171.]
   ...
   [ 59.  59.  59.]
   [ 58.  56.  57.]
   [ 58.  56.  57.]]

  [[166. 166. 174.]
   [166. 166. 174.]
   [165. 166. 171.]
   ...
   [ 57.  57.  57.]
   [ 54.  54.  54.]
   [ 57.  55.  56.]]]


 [[[154. 156. 155.]
   [155. 157. 156.]
   [156. 156. 156.]
   ...
   [ 49.  51.  50.]
   [ 56.  56.  56.]
   [ 53.  52.  50.]]

  [[153. 155. 154.]
   [155. 157. 156.]
   [152. 152. 152.]


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

photo_url  = '/content/drive/MyDrive/Colab Notebooks/Test 1 AI/AIdata_photo.npy'
labels_url = '/content/drive/MyDrive/Colab Notebooks/Test 1 AI/AIdata_label.npy'

photos = np.load(photo_url)
print("size of photos:  ",photos.shape)
labels = np.load(labels_url)
print("size of label : ",labels.shape)

photo_train,photo_test,label_train,label_test = train_test_split(photos,labels, test_size = 0.2)

print("size of photo_train: ",photo_train.shape)
print("size of photo_test:", photo_test.shape)
print("size of label_train", label_train.shape)
print("size of label_test:", label_test.shape)

print(type(label_train))
print(type(photo_train))

photo_train = photo_train.astype('float32')/255
photo_test  = photo_test.astype('float32')/255


size of photos:   (577, 192, 257, 3)
size of label :  (577, 6)
size of photo_train:  (461, 192, 257, 3)
size of photo_test: (116, 192, 257, 3)
size of label_train (461, 6)
size of label_test: (116, 6)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
from keras.models import Sequential
from keras.layers import Conv2D, Dense, LeakyReLU, MaxPooling2D, Flatten, Dropout
from keras.optimizers import Adam
from keras.losses import categorical_crossentropy

model = Sequential()
model.add(Conv2D(32, kernel_size = (3,3), activation = 'relu', input_shape = (192,257,3), padding = 'same' ))
model.add(LeakyReLU(alpha =0.1))
model.add(MaxPooling2D((2,2), padding ="same" ))
model.add(Dropout(0.25))

model.add(Conv2D(64,(3,3), activation = 'relu', padding ='same'))
model.add(LeakyReLU(alpha = 0.1))
model.add(MaxPooling2D((2,2), padding = 'same'))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(LeakyReLU(alpha = 0.1))
model.add(Dense(6,activation = 'softmax'))

model.compile(loss = categorical_crossentropy , optimizer = Adam(), metrics = ['accuracy'])
model.summary()
train = model.fit(photo_train,label_train, batch_size = 64, epochs = 10)
loss,acc = model.evaluate(photo_test,label_test)
print("Do chinh xac:  ",acc)
print("Do mat mat:  ",loss)
model.save('AIdata.h5')

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 192, 257, 32)      896       
                                                                 
 leaky_re_lu_9 (LeakyReLU)   (None, 192, 257, 32)      0         
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 96, 129, 32)      0         
 2D)                                                             
                                                                 
 dropout_6 (Dropout)         (None, 96, 129, 32)       0         
                                                                 
 conv2d_7 (Conv2D)           (None, 96, 129, 64)       18496     
                                                                 
 leaky_re_lu_10 (LeakyReLU)  (None, 96, 129, 64)       0         
                                                      